import type { Equip, Movement, Muscle } from "@/lib/constants";

export type SeedExercise = {
  slug: string;
  en: string;
  bn: string;
  muscle: Muscle;
  secondary: Muscle[];
  equipment: Equip[];
  movement: Movement;
  type: "compound" | "isolation";
  free: boolean;
  contra: string[];
  aliases: string[];
  stepsEn: string[];
  stepsBn: string[];
  mistakesEn: string[];
  mistakesBn: string[];
  tipEn: string;
  tipBn: string;
};

const ex = (
  slug: string,
  en: string,
  bn: string,
  muscle: Muscle,
  secondary: Muscle[],
  equipment: Equip[],
  movement: Movement,
  type: "compound" | "isolation",
  free: boolean,
  contra: string[],
  aliases: string[],
  stepsEn: string[],
  stepsBn: string[],
  mistakesEn: string[],
  mistakesBn: string[],
  tipEn = "",
  tipBn = "",
): SeedExercise => ({
  slug, en, bn, muscle, secondary, equipment, movement, type, free, contra, aliases,
  stepsEn, stepsBn, mistakesEn, mistakesBn, tipEn, tipBn,
});

export const SEED_EXERCISES: SeedExercise[] = [
  // ---------- CHEST ----------
  ex("push-up", "Push-up", "পুশ-আপ", "chest", ["triceps", "shoulders"], ["bodyweight"], "push", "compound", true, ["wrist"],
    ["push up", "pushup", "press up"],
    ["Hands a little wider than shoulders, body in a straight line.", "Lower your chest to just above the floor.", "Push the floor away until your arms are straight."],
    ["হাত কাঁধের চেয়ে একটু চওড়া রাখুন, শরীর সোজা রাখুন।", "বুক মেঝের কাছাকাছি নামান।", "মেঝে ঠেলে হাত সোজা করুন।"],
    ["Hips sagging down", "Elbows flared far out"],
    ["কোমর ঝুলে যাওয়া", "কনুই বেশি বাইরে ছড়িয়ে দেওয়া"],
    "Too hard? Put your hands on a bench to make it easier.", "কঠিন লাগলে হাত বেঞ্চে রেখে করুন।"),
  ex("machine-chest-press", "Machine Chest Press", "মেশিন চেস্ট প্রেস", "chest", ["triceps", "shoulders"], ["machines"], "push", "compound", true, ["shoulder"],
    ["chest press", "machine chest press", "pec press", "seated chest press"],
    ["Adjust the seat so the handles are at mid-chest height.", "Press forward until arms are nearly straight.", "Return slowly, feeling a stretch across the chest."],
    ["সিট এমনভাবে ঠিক করুন যেন হ্যান্ডেল বুকের মাঝ বরাবর থাকে।", "হাত প্রায় সোজা না হওয়া পর্যন্ত সামনে ঠেলুন।", "ধীরে ফিরিয়ে আনুন, বুকে টান অনুভব করুন।"],
    ["Seat too low or too high", "Letting the weight stack slam"],
    ["সিট খুব নিচু বা উঁচু রাখা", "ওজন ধপ করে ফেলে দেওয়া"],
    "Keep your back flat against the pad.", "পিঠ প্যাডের সাথে লাগিয়ে রাখুন।"),
  ex("db-bench-press", "Dumbbell Bench Press", "ডাম্বেল বেঞ্চ প্রেস", "chest", ["triceps", "shoulders"], ["dumbbells", "bench"], "push", "compound", true, ["shoulder"],
    ["dumbbell bench", "db bench", "dumbbell press", "dumbbell chest press"],
    ["Lie on the bench, dumbbells at chest level, feet flat.", "Press up until arms are straight above your chest.", "Lower with control until elbows are just below the bench."],
    ["বেঞ্চে শুয়ে ডাম্বেল বুক বরাবর ধরুন, পা মেঝেতে রাখুন।", "বুকের উপর হাত সোজা হওয়া পর্যন্ত ঠেলুন।", "নিয়ন্ত্রণ রেখে কনুই বেঞ্চের একটু নিচে আসা পর্যন্ত নামান।"],
    ["Bouncing the weights off the chest", "Arching the lower back too much"],
    ["ডাম্বেল বুকে ঠেকিয়ে লাফিয়ে তোলা", "কোমর বেশি বাঁকা করা"]),
  ex("barbell-bench-press", "Barbell Bench Press", "বারবেল বেঞ্চ প্রেস", "chest", ["triceps", "shoulders"], ["barbell", "bench"], "push", "compound", true, ["shoulder"],
    ["bench press", "barbell bench", "flat bench", "bench"],
    ["Lie down, eyes under the bar, grip slightly wider than shoulders.", "Lower the bar to mid-chest with control.", "Press up and slightly back to the start."],
    ["শুয়ে পড়ুন, বারের নিচে চোখ রাখুন, কাঁধের চেয়ে একটু চওড়া গ্রিপ নিন।", "নিয়ন্ত্রণ রেখে বার বুকের মাঝে নামান।", "উপরে ঠেলে শুরুর অবস্থানে ফিরুন।"],
    ["Lifting without a spotter when it is heavy", "Lifting your hips off the bench"],
    ["ভারী ওজনে স্পটার ছাড়া করা", "কোমর বেঞ্চ থেকে তুলে ফেলা"],
    "Always use safety pins or a spotter.", "সবসময় সেফটি পিন বা স্পটার ব্যবহার করুন।"),
  ex("incline-db-press", "Incline Dumbbell Press", "ইনক্লাইন ডাম্বেল প্রেস", "chest", ["shoulders", "triceps"], ["dumbbells", "bench"], "push", "compound", false, ["shoulder"],
    ["incline press", "incline dumbbell", "incline bench", "incline db"],
    ["Set the bench to a low incline (about 30°).", "Press the dumbbells up over your upper chest.", "Lower slowly to a deep, comfortable stretch."],
    ["বেঞ্চ অল্প ঢালু (প্রায় ৩০°) করুন।", "ডাম্বেল উপরের বুকের উপর ঠেলে তুলুন।", "ধীরে গভীর স্ট্রেচ পর্যন্ত নামান।"],
    ["Bench set too steep (turns into a shoulder press)", "Flaring elbows to 90°"],
    ["বেঞ্চ বেশি খাড়া করা (কাঁধের ব্যায়াম হয়ে যায়)", "কনুই ৯০° বাইরে ছড়ানো"]),
  ex("cable-fly", "Cable Fly", "কেবল ফ্লাই", "chest", ["shoulders"], ["cable"], "push", "isolation", false, ["shoulder"],
    ["cable fly", "chest fly", "pec deck", "pec fly", "fly", "flye", "cable crossover", "crossover", "dumbbell fly"],
    ["Stand between the pulleys with a slight bend in your elbows.", "Bring your hands together in a wide hugging arc.", "Return slowly until you feel a chest stretch."],
    ["পুলির মাঝে দাঁড়ান, কনুই সামান্য বাঁকানো রাখুন।", "বড় আলিঙ্গনের মতো করে দুই হাত সামনে আনুন।", "বুকে টান না লাগা পর্যন্ত ধীরে ফিরুন।"],
    ["Turning it into a press", "Going too heavy and losing control"],
    ["প্রেসের মতো করে ফেলা", "অতিরিক্ত ভারী ওজনে নিয়ন্ত্রণ হারানো"]),

  // ---------- BACK ----------
  ex("lat-pulldown", "Lat Pulldown", "ল্যাট পুলডাউন", "back", ["biceps"], ["lat_pulldown"], "pull", "compound", true, [],
    ["lat pulldown", "pulldown", "pull down", "lat pull"],
    ["Grip the bar wider than shoulders, thighs locked under the pad.", "Pull the bar to your upper chest, squeezing your shoulder blades.", "Let it rise slowly until your arms are straight."],
    ["কাঁধের চেয়ে চওড়া গ্রিপে বার ধরুন, উরু প্যাডের নিচে আটকান।", "কাঁধের হাড় চেপে বার উপরের বুক পর্যন্ত টানুন।", "ধীরে উপরে যেতে দিন যতক্ষণ না হাত সোজা হয়।"],
    ["Leaning far back and swinging", "Pulling the bar behind your neck"],
    ["অনেক পেছনে হেলে ঝাঁকি দেওয়া", "বার ঘাড়ের পেছনে টানা"],
    "Think “elbows to hips”, not “hands to chest”.", "“হাত নয়, কনুই কোমরের দিকে” ভাবুন।"),
  ex("seated-cable-row", "Seated Cable Row", "সিটেড কেবল রো", "back", ["biceps"], ["cable"], "pull", "compound", true, ["back"],
    ["seated row", "cable row", "seated cable row", "low row", "row"],
    ["Sit tall with feet braced and a slight bend in your knees.", "Pull the handle to your belly, squeezing your shoulder blades.", "Stretch forward slowly without rounding your back."],
    ["সোজা হয়ে বসুন, পা ঠেকিয়ে রাখুন, হাঁটু সামান্য বাঁকা।", "কাঁধের হাড় চেপে হ্যান্ডেল পেটের দিকে টানুন।", "পিঠ না বাঁকিয়ে ধীরে সামনে ফিরুন।"],
    ["Rocking your torso to move the weight", "Shrugging the shoulders up"],
    ["শরীর দোলাতে দোলাতে টানা", "কাঁধ উপরে তুলে ফেলা"]),
  ex("one-arm-db-row", "One-arm Dumbbell Row", "ওয়ান-আর্ম ডাম্বেল রো", "back", ["biceps"], ["dumbbells"], "pull", "compound", true, [],
    ["one arm row", "single arm row", "dumbbell row", "db row"],
    ["Place one hand and knee on a bench, back flat.", "Pull the dumbbell toward your hip.", "Lower slowly until your arm is straight."],
    ["এক হাত ও এক হাঁটু বেঞ্চে রাখুন, পিঠ সোজা।", "ডাম্বেল কোমরের দিকে টানুন।", "হাত সোজা না হওয়া পর্যন্ত ধীরে নামান।"],
    ["Twisting the torso", "Using a jerk instead of a pull"],
    ["শরীর মোচড়ানো", "টানার বদলে ঝাঁকি দেওয়া"]),
  ex("inverted-row", "Inverted Row", "ইনভার্টেড রো", "back", ["biceps"], ["bodyweight"], "pull", "compound", true, [],
    ["inverted row", "body row", "australian pull"],
    ["Lie under a sturdy table or low bar and grip the edge.", "Keep your body straight and pull your chest up to the edge.", "Lower slowly."],
    ["মজবুত টেবিল বা নিচু বারের নিচে শুয়ে কিনারা ধরুন।", "শরীর সোজা রেখে বুক কিনারা পর্যন্ত টানুন।", "ধীরে নামুন।"],
    ["Sagging hips", "Using a table that is not stable"],
    ["কোমর ঝুলে যাওয়া", "অস্থির টেবিল ব্যবহার করা"],
    "Bend your knees to make it easier.", "সহজ করতে হাঁটু বাঁকান।"),
  ex("pull-up", "Pull-up", "পুল-আপ", "back", ["biceps"], ["pullup_bar"], "pull", "compound", true, ["shoulder", "elbow"],
    ["pull up", "pullup", "chin up", "chinup", "chin-up"],
    ["Hang from the bar with hands just outside shoulders.", "Pull your chest toward the bar.", "Lower all the way with control."],
    ["কাঁধের বাইরে হাত রেখে বারে ঝুলুন।", "বুক বারের দিকে টানুন।", "নিয়ন্ত্রণ রেখে পুরোপুরি নামুন।"],
    ["Half reps", "Kicking or swinging"],
    ["অর্ধেক রেপ করা", "পা ছোঁড়া বা দোল খাওয়া"],
    "Use a resistance band or lat pulldown until you can do 5 clean reps.", "৫টি পরিষ্কার রেপ না পারা পর্যন্ত ব্যান্ড বা ল্যাট পুলডাউন ব্যবহার করুন।"),
  ex("face-pull", "Face Pull", "ফেস পুল", "back", ["shoulders"], ["cable"], "pull", "isolation", false, [],
    ["face pull", "rear delt", "reverse fly"],
    ["Set the rope at face height and step back.", "Pull the rope toward your face, elbows high.", "Squeeze the back of your shoulders, then return slowly."],
    ["দড়ি মুখ বরাবর উচ্চতায় রাখুন এবং পেছনে সরুন।", "কনুই উঁচু রেখে দড়ি মুখের দিকে টানুন।", "কাঁধের পেছনটা চেপে ধীরে ফিরুন।"],
    ["Too much weight", "Leaning back to cheat"],
    ["অতিরিক্ত ভারী ওজন", "পেছনে হেলে ফাঁকি দেওয়া"],
    "Great for posture and shoulder health.", "ভঙ্গি ও কাঁধের স্বাস্থ্যের জন্য দারুণ।"),
  ex("superman", "Superman", "সুপারম্যান", "back", ["glutes"], ["bodyweight"], "pull", "isolation", true, ["back"],
    ["superman", "back extension", "hyperextension"],
    ["Lie face down with arms stretched forward.", "Lift your arms, chest and legs a few centimetres.", "Hold for 2 seconds, then lower."],
    ["উপুড় হয়ে শুয়ে হাত সামনে বাড়ান।", "হাত, বুক ও পা কয়েক সেন্টিমিটার তুলুন।", "২ সেকেন্ড ধরে রেখে নামান।"],
    ["Lifting too high and pinching the lower back", "Holding your breath"],
    ["বেশি উঁচু করে কোমরে চাপ দেওয়া", "শ্বাস আটকে রাখা"]),
  ex("barbell-row", "Barbell Row", "বারবেল রো", "back", ["biceps", "hamstrings"], ["barbell"], "pull", "compound", true, ["back"],
    ["barbell row", "bent over row", "bent-over row", "bb row", "pendlay"],
    ["Hinge at the hips, back flat, bar hanging below your knees.", "Pull the bar to your lower ribs.", "Lower with control without rounding your back."],
    ["কোমর থেকে ঝুঁকুন, পিঠ সোজা, বার হাঁটুর নিচে ঝুলিয়ে রাখুন।", "বার নিচের পাঁজরের দিকে টানুন।", "পিঠ না বাঁকিয়ে নিয়ন্ত্রণ রেখে নামান।"],
    ["Rounding the lower back", "Standing up with each rep"],
    ["কোমর বাঁকিয়ে ফেলা", "প্রতি রেপে সোজা হয়ে যাওয়া"]),

  // ---------- SHOULDERS ----------
  ex("db-shoulder-press", "Dumbbell Shoulder Press", "ডাম্বেল শোল্ডার প্রেস", "shoulders", ["triceps"], ["dumbbells"], "push", "compound", true, ["shoulder"],
    ["dumbbell shoulder press", "shoulder press", "db shoulder", "overhead press", "military press", "ohp"],
    ["Sit or stand tall, dumbbells at shoulder height.", "Press straight up until arms are almost locked.", "Lower to ear level with control."],
    ["সোজা হয়ে বসুন বা দাঁড়ান, ডাম্বেল কাঁধ বরাবর।", "প্রায় সোজা না হওয়া পর্যন্ত উপরে ঠেলুন।", "নিয়ন্ত্রণ রেখে কান বরাবর নামান।"],
    ["Arching the lower back", "Pressing forward instead of up"],
    ["কোমর বেশি বাঁকানো", "উপরে না ঠেলে সামনে ঠেলা"]),
  ex("machine-shoulder-press", "Machine Shoulder Press", "মেশিন শোল্ডার প্রেস", "shoulders", ["triceps"], ["machines"], "push", "compound", true, ["shoulder"],
    ["machine shoulder press", "machine press shoulder"],
    ["Adjust the seat so handles start at shoulder height.", "Press up without shrugging.", "Lower slowly to the start."],
    ["সিট ঠিক করুন যেন হ্যান্ডেল কাঁধ বরাবর থাকে।", "কাঁধ না তুলে উপরে ঠেলুন।", "ধীরে শুরুর অবস্থানে ফিরুন।"],
    ["Seat too low", "Bouncing the weights"],
    ["সিট খুব নিচু রাখা", "ওজন লাফিয়ে তোলা"]),
  ex("lateral-raise", "Lateral Raise", "ল্যাটারাল রেইজ", "shoulders", [], ["dumbbells"], "push", "isolation", true, [],
    ["lateral raise", "side raise", "side lateral"],
    ["Stand holding light dumbbells at your sides.", "Raise your arms out to shoulder height, elbows soft.", "Lower slowly."],
    ["হালকা ডাম্বেল নিয়ে পাশে হাত রেখে দাঁড়ান।", "কনুই সামান্য বাঁকা রেখে কাঁধ বরাবর হাত তুলুন।", "ধীরে নামান।"],
    ["Swinging the body", "Going too heavy"],
    ["শরীর দোলানো", "বেশি ভারী ওজন নেওয়া"],
    "Light weight, perfect form beats heavy swinging.", "ভারী ঝাঁকির চেয়ে হালকা ওজনে সঠিক ফর্ম ভালো।"),
  ex("pike-push-up", "Pike Push-up", "পাইক পুশ-আপ", "shoulders", ["triceps"], ["bodyweight"], "push", "compound", true, ["shoulder", "wrist"],
    ["pike push", "pike"],
    ["Start in a push-up position, hips high in an upside-down V.", "Bend elbows to lower your head toward the floor.", "Push back up."],
    ["পুশ-আপ পজিশনে কোমর উঁচু করে উল্টো V আকার নিন।", "কনুই বাঁকিয়ে মাথা মেঝের দিকে নামান।", "ঠেলে উপরে উঠুন।"],
    ["Hips too low", "Going too fast"],
    ["কোমর নিচু রাখা", "খুব দ্রুত করা"]),

  // ---------- ARMS ----------
  ex("db-curl", "Dumbbell Curl", "ডাম্বেল কার্ল", "biceps", [], ["dumbbells"], "pull", "isolation", true, [],
    ["dumbbell curl", "bicep curl", "biceps curl", "barbell curl", "curl", "ez bar curl"],
    ["Stand tall, elbows tucked at your sides.", "Curl the weights up without swinging.", "Lower for 2–3 seconds."],
    ["সোজা দাঁড়ান, কনুই শরীরের পাশে লাগানো।", "ঝাঁকি না দিয়ে ডাম্বেল উপরে তুলুন।", "২–৩ সেকেন্ড ধরে নামান।"],
    ["Swinging the torso", "Moving the elbows forward"],
    ["শরীর দোলানো", "কনুই সামনে নিয়ে আসা"]),
  ex("hammer-curl", "Hammer Curl", "হ্যামার কার্ল", "biceps", [], ["dumbbells"], "pull", "isolation", true, [],
    ["hammer curl", "hammer"],
    ["Hold dumbbells with palms facing each other.", "Curl up keeping your wrists straight.", "Lower slowly."],
    ["হাতের তালু পরস্পরের দিকে রেখে ডাম্বেল ধরুন।", "কব্জি সোজা রেখে উপরে তুলুন।", "ধীরে নামান।"],
    ["Using momentum", "Bending the wrists"],
    ["গতির সাহায্য নেওয়া", "কব্জি বাঁকানো"]),
  ex("cable-curl", "Cable Curl", "কেবল কার্ল", "biceps", [], ["cable"], "pull", "isolation", false, [],
    ["cable curl", "preacher curl", "preacher"],
    ["Stand facing the low pulley, elbows at your sides.", "Curl the handle up.", "Lower slowly, keeping tension."],
    ["নিচু পুলির দিকে মুখ করে দাঁড়ান, কনুই পাশে।", "হ্যান্ডেল উপরে কার্ল করুন।", "টান ধরে রেখে ধীরে নামান।"],
    ["Leaning back", "Dropping the weight fast"],
    ["পেছনে হেলে যাওয়া", "দ্রুত ওজন ছেড়ে দেওয়া"]),
  ex("triceps-pushdown", "Triceps Pushdown", "ট্রাইসেপ পুশডাউন", "triceps", [], ["cable"], "push", "isolation", true, ["elbow"],
    ["triceps pushdown", "tricep pushdown", "pushdown", "push down", "rope extension", "skull crusher", "skullcrusher", "triceps extension", "tricep extension"],
    ["Stand at the high pulley, elbows glued to your sides.", "Push the handle down until arms are straight.", "Let it rise slowly to chest height."],
    ["উঁচু পুলির সামনে দাঁড়ান, কনুই শরীরের সাথে লাগান।", "হাত সোজা না হওয়া পর্যন্ত হ্যান্ডেল নিচে ঠেলুন।", "ধীরে বুক বরাবর উঠতে দিন।"],
    ["Elbows drifting forward", "Leaning over the bar"],
    ["কনুই সামনে সরে যাওয়া", "বারের উপর ঝুঁকে পড়া"]),
  ex("bench-dip", "Bench Dip", "বেঞ্চ ডিপ", "triceps", ["shoulders", "chest"], ["bodyweight"], "push", "isolation", true, ["shoulder", "wrist", "elbow"],
    ["bench dip", "dips", "dip", "tricep dip", "triceps dip"],
    ["Hands on a bench behind you, feet on the floor.", "Bend your elbows to about 90°.", "Push back up."],
    ["পেছনে বেঞ্চে হাত রাখুন, পা মেঝেতে।", "কনুই প্রায় ৯০° বাঁকান।", "ঠেলে উপরে উঠুন।"],
    ["Going too deep (shoulder strain)", "Hips drifting far from the bench"],
    ["অতিরিক্ত নিচে নামা (কাঁধে চাপ)", "কোমর বেঞ্চ থেকে অনেক দূরে যাওয়া"]),
  ex("db-overhead-triceps", "Overhead Triceps Extension", "ওভারহেড ট্রাইসেপ এক্সটেনশন", "triceps", [], ["dumbbells"], "push", "isolation", false, ["shoulder", "elbow"],
    ["overhead triceps", "overhead tricep", "overhead extension", "french press"],
    ["Hold one dumbbell overhead with both hands.", "Bend elbows to lower it behind your head.", "Extend back up."],
    ["দুই হাতে একটি ডাম্বেল মাথার উপরে ধরুন।", "কনুই বাঁকিয়ে মাথার পেছনে নামান।", "আবার সোজা করুন।"],
    ["Elbows flaring wide", "Arching the back"],
    ["কনুই বাইরে ছড়ানো", "পিঠ বাঁকা করা"]),

  // ---------- LEGS ----------
  ex("bodyweight-squat", "Bodyweight Squat", "বডিওয়েট স্কোয়াট", "quads", ["glutes", "hamstrings"], ["bodyweight"], "legs", "compound", true, [],
    ["bodyweight squat", "air squat"],
    ["Feet shoulder-width apart, chest up.", "Sit back and down as if onto a chair.", "Drive through your heels to stand."],
    ["পা কাঁধ-সমান ফাঁকা, বুক উঁচু।", "চেয়ারে বসার মতো পেছনে ও নিচে নামুন।", "গোড়ালি দিয়ে ঠেলে উঠুন।"],
    ["Knees caving in", "Heels lifting off the floor"],
    ["হাঁটু ভেতরে ঢুকে যাওয়া", "গোড়ালি মেঝে থেকে উঠে যাওয়া"],
    "Squat only as deep as you feel no pain.", "যতটা নামলে ব্যথা লাগে না ততটাই নামুন।"),
  ex("goblet-squat", "Goblet Squat", "গবলেট স্কোয়াট", "quads", ["glutes"], ["dumbbells"], "legs", "compound", true, [],
    ["goblet squat", "goblet"],
    ["Hold one dumbbell against your chest.", "Squat down between your knees, chest tall.", "Stand up by pushing the floor away."],
    ["একটি ডাম্বেল বুকের সাথে ধরুন।", "বুক সোজা রেখে হাঁটুর মাঝ দিয়ে নিচে নামুন।", "মেঝে ঠেলে উঠে দাঁড়ান।"],
    ["Leaning forward", "Knees collapsing inward"],
    ["সামনে ঝুঁকে যাওয়া", "হাঁটু ভেতরে ভেঙে যাওয়া"],
    "The best squat to learn first.", "প্রথমে শেখার জন্য সেরা স্কোয়াট।"),
  ex("leg-press", "Leg Press", "লেগ প্রেস", "quads", ["glutes", "hamstrings"], ["leg_press"], "legs", "compound", true, [],
    ["leg press"],
    ["Sit with your back flat against the pad, feet shoulder-width on the platform.", "Lower until knees are about 90°.", "Press up without locking your knees."],
    ["পিঠ প্যাডে সোজা রেখে বসুন, পা প্ল্যাটফর্মে কাঁধ-সমান ফাঁকা।", "হাঁটু প্রায় ৯০° না হওয়া পর্যন্ত নামুন।", "হাঁটু লক না করে ঠেলুন।"],
    ["Lower back lifting off the pad", "Locking out the knees hard"],
    ["কোমর প্যাড থেকে উঠে যাওয়া", "জোরে হাঁটু লক করা"],
    "Start light, this machine can load very heavy, very fast.", "হালকা দিয়ে শুরু করুন, এই মেশিনে দ্রুত অনেক ভারী হয়ে যায়।"),
  ex("barbell-squat", "Barbell Squat", "বারবেল স্কোয়াট", "quads", ["glutes", "hamstrings", "core"], ["barbell"], "legs", "compound", true, ["knee", "back"],
    ["barbell squat", "back squat", "squat", "front squat", "smith squat"],
    ["Bar on your upper back, feet shoulder-width, chest up.", "Sit down between your hips until thighs are parallel.", "Drive up through mid-foot."],
    ["বার উপরের পিঠে, পা কাঁধ-সমান, বুক উঁচু।", "উরু মেঝের সমান্তরাল না হওয়া পর্যন্ত বসুন।", "পায়ের মাঝখান দিয়ে ঠেলে উঠুন।"],
    ["Rounding the lower back", "Going heavy before form is solid"],
    ["কোমর বাঁকানো", "ফর্ম ঠিক হওয়ার আগেই ভারী ওজন নেওয়া"],
    "Learn it with the goblet squat first. Use safety pins.", "আগে গবলেট স্কোয়াট শিখুন। সেফটি পিন ব্যবহার করুন।"),
  ex("walking-lunge", "Lunge", "লাঞ্জ", "quads", ["glutes", "hamstrings"], ["bodyweight"], "legs", "compound", true, ["knee"],
    ["lunge", "walking lunge"],
    ["Step forward and lower your back knee toward the floor.", "Keep your front knee over your mid-foot.", "Push off the front foot and step together."],
    ["সামনে এগিয়ে পেছনের হাঁটু মেঝের দিকে নামান।", "সামনের হাঁটু পায়ের মাঝ বরাবর রাখুন।", "সামনের পা দিয়ে ঠেলে পা এক করুন।"],
    ["Steps too short", "Knee collapsing inward"],
    ["পদক্ষেপ খুব ছোট", "হাঁটু ভেতরে ঢুকে যাওয়া"]),
  ex("bulgarian-split-squat", "Bulgarian Split Squat", "বুলগেরিয়ান স্প্লিট স্কোয়াট", "quads", ["glutes"], ["dumbbells", "bench"], "legs", "compound", false, ["knee"],
    ["bulgarian", "split squat"],
    ["Rest your back foot on a bench behind you.", "Lower straight down until the front thigh is parallel.", "Drive up through the front heel."],
    ["পেছনের পা বেঞ্চে রাখুন।", "সোজা নিচে নামুন যতক্ষণ সামনের উরু সমান্তরাল হয়।", "সামনের গোড়ালি দিয়ে ঠেলে উঠুন।"],
    ["Standing too close to the bench", "Leaning too far forward"],
    ["বেঞ্চের খুব কাছে দাঁড়ানো", "অতিরিক্ত সামনে ঝোঁকা"]),
  ex("leg-extension", "Leg Extension", "লেগ এক্সটেনশন", "quads", [], ["machines"], "legs", "isolation", true, ["knee"],
    ["leg extension", "quad extension"],
    ["Adjust the pad just above your ankles.", "Straighten your knees, squeezing your thighs.", "Lower slowly."],
    ["প্যাড গোড়ালির একটু উপরে ঠিক করুন।", "উরু চেপে হাঁটু সোজা করুন।", "ধীরে নামান।"],
    ["Kicking the weight up", "Lifting the hips"],
    ["ওজন লাথি মেরে তোলা", "কোমর তুলে ফেলা"]),
  ex("romanian-deadlift-db", "Romanian Deadlift", "রোমানিয়ান ডেডলিফ্ট", "hamstrings", ["glutes", "back"], ["dumbbells"], "legs", "compound", false, ["back"],
    ["romanian deadlift", "rdl", "deadlift", "stiff leg", "good morning"],
    ["Hold dumbbells in front of your thighs, knees soft.", "Push your hips back, sliding the weights down your legs.", "Stand tall by squeezing your glutes."],
    ["ডাম্বেল উরুর সামনে ধরুন, হাঁটু সামান্য বাঁকা।", "কোমর পেছনে ঠেলুন, ডাম্বেল পা বেয়ে নামান।", "নিতম্ব চেপে সোজা হয়ে দাঁড়ান।"],
    ["Rounding the back", "Squatting instead of hinging"],
    ["পিঠ বাঁকানো", "কোমর পেছনে না ঠেলে স্কোয়াটের মতো বসা"],
    "Stop when you feel a hamstring stretch.", "পেছনের উরুতে টান লাগলেই থামুন।"),
  ex("leg-curl", "Leg Curl", "লেগ কার্ল", "hamstrings", [], ["machines"], "legs", "isolation", true, [],
    ["leg curl", "hamstring curl", "lying curl", "seated curl"],
    ["Adjust the pad just above your heels.", "Curl your heels toward your glutes.", "Return slowly."],
    ["প্যাড গোড়ালির উপরে ঠিক করুন।", "গোড়ালি নিতম্বের দিকে টানুন।", "ধীরে ফিরুন।"],
    ["Lifting the hips", "Dropping the weight quickly"],
    ["কোমর তুলে ফেলা", "দ্রুত ওজন ছেড়ে দেওয়া"]),
  ex("glute-bridge", "Glute Bridge", "গ্লুট ব্রিজ", "glutes", ["hamstrings"], ["bodyweight"], "legs", "compound", true, [],
    ["glute bridge", "bridge"],
    ["Lie on your back, knees bent, feet flat.", "Push through your heels and lift your hips.", "Squeeze at the top, then lower."],
    ["চিত হয়ে শুয়ে হাঁটু ভাঁজ করুন, পা মেঝেতে।", "গোড়ালি দিয়ে ঠেলে কোমর তুলুন।", "উপরে নিতম্ব চেপে ধরে নামান।"],
    ["Arching the lower back", "Pushing with toes"],
    ["কোমর বেশি বাঁকানো", "পায়ের আঙুল দিয়ে ঠেলা"],
    "A knee-friendly way to train legs.", "হাঁটুর জন্য নিরাপদ পায়ের ব্যায়াম।"),
  ex("hip-thrust", "Hip Thrust", "হিপ থ্রাস্ট", "glutes", ["hamstrings"], ["barbell", "bench"], "legs", "compound", false, [],
    ["hip thrust", "thrust"],
    ["Upper back on a bench, bar across your hips.", "Drive your hips up until your body is flat.", "Lower with control."],
    ["উপরের পিঠ বেঞ্চে, বার কোমরের উপর।", "শরীর সমান না হওয়া পর্যন্ত কোমর ঠেলে তুলুন।", "নিয়ন্ত্রণ রেখে নামান।"],
    ["Overarching the back", "Feet too far or too close"],
    ["পিঠ বেশি বাঁকানো", "পা বেশি দূরে বা কাছে রাখা"],
    "Pad the bar with a folded towel.", "বারে ভাঁজ করা তোয়ালে দিন।"),
  ex("calf-raise", "Calf Raise", "কাফ রেইজ", "calves", [], ["bodyweight"], "legs", "isolation", true, [],
    ["calf raise", "calf", "calves"],
    ["Stand on the edge of a step, heels hanging.", "Rise onto your toes as high as you can.", "Lower slowly below the step."],
    ["সিঁড়ির কিনারায় দাঁড়ান, গোড়ালি ঝুলিয়ে।", "যতটা পারেন আঙুলের উপর উঠুন।", "ধীরে সিঁড়ির নিচে পর্যন্ত নামুন।"],
    ["Bouncing", "Short range of motion"],
    ["লাফিয়ে করা", "কম দূরত্ব চলা"]),

  // ---------- CORE ----------
  ex("plank", "Plank", "প্ল্যাঙ্ক", "core", ["shoulders"], ["bodyweight"], "core", "isolation", true, [],
    ["plank"],
    ["Forearms on the floor, body in a straight line.", "Squeeze your abs and glutes.", "Hold 20–45 seconds, breathing normally."],
    ["কনুই থেকে হাত মেঝেতে, শরীর সোজা।", "পেট ও নিতম্ব শক্ত রাখুন।", "স্বাভাবিক শ্বাসে ২০–৪৫ সেকেন্ড ধরে থাকুন।"],
    ["Hips too high or too low", "Holding your breath"],
    ["কোমর বেশি উঁচু বা নিচু", "শ্বাস আটকে রাখা"]),
  ex("dead-bug", "Dead Bug", "ডেড বাগ", "core", [], ["bodyweight"], "core", "isolation", true, [],
    ["dead bug"],
    ["Lie on your back, arms up, knees bent over hips.", "Lower the opposite arm and leg slowly.", "Keep your lower back pressed into the floor."],
    ["চিত হয়ে শুয়ে হাত উপরে, হাঁটু কোমরের উপরে ভাঁজ করুন।", "উল্টো হাত ও পা ধীরে নামান।", "কোমর মেঝেতে চেপে রাখুন।"],
    ["Lower back arching off the floor", "Moving too fast"],
    ["কোমর মেঝে থেকে উঠে যাওয়া", "খুব দ্রুত করা"],
    "Friendly for bad backs.", "কোমরের সমস্যায়ও নিরাপদ।"),
  ex("cable-crunch", "Cable Crunch", "কেবল ক্রাঞ্চ", "core", [], ["cable"], "core", "isolation", false, ["back"],
    ["cable crunch", "crunch", "sit up", "situp", "leg raise", "ab wheel", "russian twist"],
    ["Kneel facing the high pulley, rope by your head.", "Curl your ribs toward your hips.", "Return slowly."],
    ["উঁচু পুলির সামনে হাঁটু গেড়ে বসুন, দড়ি মাথার কাছে।", "পাঁজর কোমরের দিকে কুঁচকে আনুন।", "ধীরে ফিরুন।"],
    ["Pulling with the arms", "Sitting back onto the heels"],
    ["হাত দিয়ে টানা", "গোড়ালির উপর বসে যাওয়া"]),
];
