import Link from "next/link";
import { getLang } from "@/lib/session";
import { LangToggle } from "@/components/lang-toggle";
import { btnGhost, btnPrimary, Disclaimer, Eyebrow } from "@/components/ui";
import { Reveal, PointerGlow, ScrollProgress } from "@/components/motion";
import { pick } from "@/lib/constants";

export const dynamic = "force-dynamic";

const pillars = [
  { n: "01", title: "A plan that fits your week", body: "Tell us your goal, schedule, equipment and limitations. GymSathi builds one clear beginner plan with a reason behind every movement." },
  { n: "02", title: "Confidence inside the gym", body: "Gym Mode keeps the next set, rest timer and form cue in one calm screen that works when the signal disappears." },
  { n: "03", title: "Proof you are improving", body: "Your workout history, streak, personal bests and body weight make progress visible before motivation fades." },
];

const features = [
  ["PLAN", "Rule-based beginner plans", "Full body for two or three days, upper/lower only when your schedule can support it."],
  ["MOVE", "Equipment-aware swaps", "If a machine is busy or missing, choose a reviewed alternative with the same movement pattern."],
  ["LOG", "Offline Gym Mode", "Save sets, reps, loads and notes on the gym floor. Sync status stays visible."],
  ["LEARN", "Bangla + English cues", "Simple setup, execution and stop cues for the exercises in your plan."],
  ["CHECK", "Manual Plan Auditor", "Paste a routine and get a structured second opinion on balance, volume and rep ranges."],
  ["START", "First-day orientation", "A short guide for machines, etiquette, safety and what to expect on day one."],
];

function Logo() {
  return <Link href="/" className="group flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#c7f36b] text-sm font-black text-[#08100f] transition group-hover:rotate-6">GS</span><span className="font-semibold tracking-[-0.03em]">Gym<span className="text-[#c7f36b]">Sathi</span></span></Link>;
}

function MiniDashboard() {
  return <div className="glass shine relative mx-auto w-full max-w-[510px] rounded-[2rem] p-3 shadow-[0_30px_100px_rgba(0,0,0,.36)]"><div className="rounded-[1.5rem] bg-[#0c1715] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#8f9b96]">Today · Wednesday</p><h3 className="mt-2 text-2xl font-bold tracking-[-0.04em]">Upper body A</h3></div><span className="grid h-10 w-10 place-items-center rounded-full border border-[#c7f36b]/30 bg-[#c7f36b]/10 text-xs font-bold text-[#c7f36b]">64%</span></div><div className="mt-6 rounded-2xl border border-white/8 bg-white/[0.035] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Dumbbell bench press</p><p className="mt-1 text-xs text-[#8f9b96]">3 sets · 8–12 reps · Chest</p></div><span className="text-xs text-[#c7f36b]">01</span></div><div className="mt-4 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#c7f36b]" /><span className="h-2 w-2 rounded-full bg-[#c7f36b]" /><span className="h-2 w-2 rounded-full bg-white/15" /><span className="ml-auto text-xs text-[#8f9b96]">Rest 01:18</span></div></div><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-xl border border-white/8 bg-white/[0.03] p-3"><p className="text-[10px] text-[#8f9b96]">THIS WEEK</p><p className="mt-1 text-lg font-bold">2/3</p></div><div className="rounded-xl border border-white/8 bg-white/[0.03] p-3"><p className="text-[10px] text-[#8f9b96]">STREAK</p><p className="mt-1 text-lg font-bold">3 wks</p></div><div className="rounded-xl border border-white/8 bg-white/[0.03] p-3"><p className="text-[10px] text-[#8f9b96]">SYNC</p><p className="mt-1 text-lg font-bold text-[#8cebd9]">Ready</p></div></div><div className="mt-5 flex items-center gap-3 rounded-xl bg-[#c7f36b] p-3 text-[#08100f]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-black/10 text-sm">→</span><div><p className="text-xs font-bold uppercase tracking-[0.12em]">Next best action</p><p className="text-sm font-semibold">Start your first set</p></div></div></div></div>;
}

export default async function LandingPage() {
  const lang = await getLang();
  const T = (en: string, bn: string) => pick(lang, en, bn);
  return <main className="relative overflow-hidden"><ScrollProgress /><PointerGlow /><div className="site-grid pointer-events-none absolute inset-x-0 top-0 h-[780px] opacity-70" /><div className="relative z-10 mx-auto max-w-6xl px-5 pb-20 sm:px-8">
    <header className="flex items-center justify-between py-6"><Logo /><div className="flex items-center gap-3"><Link href="#how-it-works" className="hidden text-sm text-[#8f9b96] transition hover:text-white sm:block">How it works</Link><LangToggle lang={lang} /><Link href="/onboarding" className="hidden rounded-xl border border-white/12 px-3 py-2 text-xs font-semibold transition hover:border-white/25 hover:bg-white/5 sm:block">Open app</Link></div></header>
    <section className="grid items-center gap-12 pb-20 pt-16 lg:grid-cols-[1.03fr_.97fr] lg:gap-16 lg:pb-28 lg:pt-24"><Reveal><Eyebrow>{T("The beginner gym companion · Bangladesh", "বাংলাদেশের নতুনদের জিম সঙ্গী")}</Eyebrow><h1 className="max-w-3xl text-5xl font-semibold leading-[0.98] tracking-[-0.065em] sm:text-7xl">Walk in knowing <span className="text-[#c7f36b]">what to do next.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#aab5b0]">{T("GymSathi turns a few honest answers into a calm, structured workout you can actually finish. No trainer jargon. No random routines.", "আপনার লক্ষ্য, সময় আর সরঞ্জাম বুঝে GymSathi সহজ ও পরিষ্কার ওয়ার্কআউট প্ল্যান তৈরি করে।")}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/onboarding" className={btnPrimary + " px-6 py-3.5"}>Build my free plan <span aria-hidden>↗</span></Link><Link href="#how-it-works" className={btnGhost}>See the loop <span aria-hidden>↓</span></Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[#8f9b96]"><span className="flex items-center gap-2"><span className="pulse-dot h-2 w-2 rounded-full bg-[#c7f36b]" />Guest-first · no sign-up</span><span>Bangla + English cues</span><span>Offline-ready</span></div></Reveal><Reveal delay={140}><div className="float-slow relative"><div className="absolute -inset-8 rounded-full bg-[#c7f36b]/[0.07] blur-3xl" /><MiniDashboard /><div className="glass absolute -bottom-5 -left-4 hidden rounded-2xl px-4 py-3 sm:block"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#8f9b96]">Pilot principle</p><p className="mt-1 text-sm font-semibold">One active plan. Less noise.</p></div></div></Reveal></section>
    <Reveal><div className="grid gap-4 border-y border-white/8 py-7 sm:grid-cols-3">{[["01", "2 min", "to your first plan"], ["60–100", "reviewed", "exercise records"], ["P0", "free", "closed pilot"]].map(([big, mid, small]) => <div key={big} className="flex items-baseline gap-2 sm:block"><span className="text-3xl font-semibold tracking-[-0.05em] text-[#c7f36b]">{big}</span><span className="text-sm font-semibold text-white">{mid}</span><span className="text-sm text-[#8f9b96] sm:ml-2">{small}</span></div>)}</div></Reveal>
    <section id="how-it-works" className="scroll-mt-16 py-24"><Reveal><Eyebrow>{T("A better first month", "প্রথম মাসটা সহজ হোক")}</Eyebrow><h2 className="max-w-2xl text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Less guessing. More sessions you can finish.</h2></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-3">{pillars.map((item, i) => <Reveal key={item.n} delay={i * 90}><article className="glass shine h-full rounded-[1.5rem] p-6"><div className="flex items-center justify-between"><span className="text-xs font-bold tracking-[0.18em] text-[#c7f36b]">{item.n}</span><span className="text-xl text-white/25">↗</span></div><h3 className="mt-14 max-w-xs text-xl font-semibold tracking-[-0.035em]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#8f9b96]">{item.body}</p></article></Reveal>)}</div></section>
    <section className="pb-24"><Reveal><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Eyebrow>Inside the pilot</Eyebrow><h2 className="max-w-2xl text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Everything needed for the core loop.</h2></div><p className="max-w-xs text-sm leading-6 text-[#8f9b96]">Designed for a Bangladeshi beginner on an everyday Android phone.</p></div></Reveal><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{features.map(([tag, title, body], i) => <Reveal key={tag} delay={i * 60}><article className="glass shine rounded-[1.35rem] p-5 transition hover:-translate-y-1"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-[0.2em] text-[#8f9b96]">{tag}</span><span className="text-sm text-[#c7f36b]">✦</span></div><h3 className="mt-8 text-lg font-semibold tracking-[-0.02em]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#8f9b96]">{body}</p></article></Reveal>)}</div></section>
    <section className="pb-24"><Reveal><div className="relative overflow-hidden rounded-[2rem] border border-[#c7f36b]/25 bg-[#c7f36b]/[0.08] p-7 sm:p-10"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[#c7f36b]/10 blur-3xl" /><div className="relative flex flex-col items-start justify-between gap-8 sm:flex-row sm:items-end"><div><Eyebrow>Start with one good session</Eyebrow><h2 className="max-w-2xl text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Your first plan is waiting.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-[#aab5b0]">Answer seven quick questions. Keep your plan as a guest. Change your language any time.</p></div><Link href="/onboarding" className={btnPrimary + " shrink-0 px-6 py-3.5"}>Get started <span aria-hidden>↗</span></Link></div></div></Reveal></section>
    <footer className="flex flex-col gap-4 border-t border-white/8 pt-6 text-xs text-[#8f9b96] sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Logo /><span className="hidden text-[#6f7b76] sm:inline">Built for the first 90 days.</span></div><div className="flex items-center gap-4"><Link href="/app/guide" className="hover:text-white">First-day guide</Link><Link href="/app/audit" className="hover:text-white">Plan Auditor</Link></div></footer><Disclaimer lang={lang} />
  </div></main>;
}
